### ISSUE TITLE
Calling double free results in segmentation fault

### ISSUE THREAD

**Issue by czarny247** [HappyCerberus/article-cpp20-coroutines#1]
Explicit destruction here: [https://github.com/HappyCerberus/article-cpp20-coroutines/blob/c0a6e804f0e9bd70cfa632d7d562ba1f787ade62/simplest/simplest-fixed_instrumented.cc#L58](https://github.com/HappyCerberus/article-cpp20-coroutines/blob/c0a6e804f0e9bd70cfa632d7d562ba1f787ade62/simplest/simplest-fixed_instrumented.cc#L58)

Implicit caused by returning `std::suspend_never`: [https://github.com/HappyCerberus/article-cpp20-coroutines/blob/c0a6e804f0e9bd70cfa632d7d562ba1f787ade62/simplest/simplest-fixed_instrumented.cc#L27](https://github.com/HappyCerberus/article-cpp20-coroutines/blob/c0a6e804f0e9bd70cfa632d7d562ba1f787ade62/simplest/simplest-fixed_instrumented.cc#L27)

compiled using: `g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0`

![image](https://github.com/HappyCerberus/article-cpp20-coroutines/assets/7014909/ec9f5f2e-9269-4fa9-b66e-895e76bf388a)

Fix: change to `std::suspend_always` or don't call destroy on handle in Task d-tor (not sure which one makes more sense in this example, just started learning about coroutines).

**Comment by HappyCerberus** [comment]
I need to write a new version of the article. Yes, I know about this bug.

**Comment by HappyCerberus** [comment]
I have added a warning to both the repository and the article, pointing to a more up-to-date article.

I still need to write an updated article covering the details, but this should be a better solution for now.
